version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./myapp:/usr/src/myapp
    ports:
      - "2000:2000" # Expose port 2000 for the myapp app
    networks:
      - my-network

  nginx-proxy:
    image: nginx
    ports:
      - "80:80" # Expose port 80 for the Nginx proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my-network

networks:
  my-network:
